### ISSUE TITLE
CLion plugin fails to build with 2020.1.2

### ISSUE THREAD

**Issue by mattgodbolt** [bazelbuild/intellij#1894]
Trying to get a version I can load into a contemporary CLion:

```
$ bazel build //clwb:clwb_bazel_zip --define=ij_product=clion-2020.1
Starting local Bazel server and connecting to it...
INFO: Analyzed target //clwb:clwb_bazel_zip (58 packages loaded, 1769 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/mgodbolt/.cache/bazel/_bazel_mgodbolt/14cea374caf47f5cf30d8b8eda3abb84/sandbox
ERROR: /home/mgodbolt/dev/oss/intellij/cpp/BUILD:17:13: Building cpp/libcpp.jar (35 source files) and running annotation processors (AutoAnnotationProcessor, AutoOneOfProcessor, AutoValueProcessor) failed (Exit 1)
cpp/src/com/google/idea/blaze/cpp/BlazeResolveConfiguration.java:125: error: method getAllHeaderRoots in class OCImportGraph cannot be applied to given types;
    Collection<VirtualFile> roots = OCImportGraph.getAllHeaderRoots(project, headerFile);
```

That was as of beaa17e5

I just pulled to 71fa109f and now:

```
~/d/o/intellij (master|✔) 0.8s $ bazel build //clwb:clwb_bazel_zip --define=ij_product=clion-2020.1
INFO: Analyzed target //clwb:clwb_bazel_zip (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/mgodbolt/dev/oss/intellij/clwb/BUILD:42:13: Building clwb/libclwb_lib.jar (30 source files) failed (Exit 1)
clwb/src/com/google/idea/blaze/clwb/run/BlazeCppRunner.java:25: error: cannot inherit from final CLionRunner
public class BlazeCppRunner extends CLionRunner {
                                    ^
clwb/src/com/google/idea/blaze/clwb/BlazeCppModuleType.java:53: error: cannot find symbol
    return AllIcons.Modules.SourceFolder;
                           ^
  symbol:   variable SourceFolder
  location: class Modules
clwb/src/com/google/idea/blaze/clwb/ToolchainUtils.java:28: error: cannot find symbol
      toolchain.setName(Toolchain.DEFAULT);
                                 ^
  symbol:   variable DEFAULT
  location: class Toolchain
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrLauncher.java:324: error: reference to CidrConsoleBuilder is ambiguous
    return new CidrConsoleBuilder(
           ^
  both constructor CidrConsoleBuilder(Project,CidrToolEnvironment,File) in CidrConsoleBuilder and constructor CidrConsoleBuilder(Project,CidrToolEnvironment,Path) in CidrConsoleBuilder match
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrLauncher.java:347: error: reference to CidrConsoleBuilder is ambiguous
      super(project, /* CidrToolEnvironment */ null, /* baseDir */ null);
      ^
  both constructor CidrConsoleBuilder(Project,CidrToolEnvironment,File) in CidrConsoleBuilder and constructor CidrConsoleBuilder(Project,CidrToolEnvironment,Path) in CidrConsoleBuilder match
Target //clwb:clwb_bazel_zip failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.905s, Critical Path: 2.62s
INFO: 2 processes: 1 linux-sandbox, 1 worker.
FAILED: Build did NOT complete successfully
```

**Comment by bpowers** [comment]
I also am seeing this

**Comment by JunjiUmeno** [comment]
intellij IDE 2020.x not supported yet? My IDE such that GoLand, IDEA, .. can't find out this plugin and failed to install from download.

**Comment by sunqi1993** [comment]
me too...

**Comment by austince** [comment]
https://github.com/bazelbuild/intellij/issues/1567

**Comment by kayasoze** [comment]
Fixed.

**Comment by alice-ks** [comment]
Plugin versions 2020.09.16.0.6+ are compatible with CLion 2020.1. Hence, I'm closing this issue now. Please refer to other existing tracking issues if you're interested in support for newer CLion versions.
